"""
src/report.py - Generate Markdown reports and GitHub issue drafts from analysis results.
"""

import sys
import json
import argparse


def generate_markdown_report(data: dict) -> str:
    """Convert analysis JSON into structured Markdown report / issue draft."""
    category = data.get("failure_category", "Unknown")
    summary = data.get("summary", "N/A")
    root_cause = data.get("root_cause", "N/A")
    fix = data.get("recommended_fix", "N/A")
    confidence = data.get("confidence_score", 0.0)

    report_md = f"""# ⚠️ Flaky Test Analysis Report

## Summary
**Category:** `{category}`  
**Confidence Score:** `{confidence * 100:.1f}%`  
**Description:** {summary}

---

## 🔍 Root Cause Analysis
{root_cause}

---

## 🛠️ Recommended Action / Fix
{fix}

---

## 📝 GitHub Issue Draft

```markdown
### Title: [Flake] {category} in CI Workflow

**Flake Details:**
- **Category:** {category}
- **Root Cause:** {root_cause}
- **Suggested Resolution:** {fix}

*Automated report generated by [ci-flake-agent](https://github.com/RK0297/ci-flake-agent).*
```
"""
    return report_md


def main():
    parser = argparse.ArgumentParser(description="Generate markdown report from analysis JSON.")
    parser.add_argument("--input", required=True, help="Path to analysis JSON file")
    parser.add_argument("--output", default="reports/sample_report.md", help="Path to output markdown report")

    args = parser.parse_args()

    try:
        with open(args.input, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error reading {args.input}: {e}", file=sys.stderr)
        sys.exit(1)

    report_md = generate_markdown_report(data)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(report_md)

    print(f"Successfully generated report at {args.output}")


if __name__ == "__main__":
    main()
