"""
src/report.py - Generate Markdown reports, GitHub issue drafts, and API comments from analysis results.
"""

import os
import sys
import json
import argparse
import subprocess
import requests


def get_auth_token(provided_token: str = None) -> str:
    """Retrieve GitHub token from argument, environment variable, or git credentials helper."""
    if provided_token:
        return provided_token
    token = os.getenv("GITHUB_TOKEN") or os.getenv("GH_TOKEN")
    if token:
        return token
    try:
        proc = subprocess.run(
            ['git', 'credential', 'fill'],
            input=b'protocol=https\nhost=github.com\n',
            capture_output=True,
            timeout=5
        )
        for line in proc.stdout.decode('utf-8', errors='ignore').splitlines():
            if line.startswith('password='):
                return line.split('=', 1)[1]
    except Exception:
        pass
    return ""


def format_category_badge(category: str) -> str:
    """Format category string into markdown code badge."""
    badges = {
        "race_condition": "`⚡ race_condition`",
        "network_timeout": "`⏱️ network_timeout`",
        "infra_failure": "`📡 infra_failure`",
        "real_bug": "`🐛 real_bug`"
    }
    return badges.get(category.lower(), f"`{category}`")


def generate_markdown_report(data_input) -> str:
    """
    Generate comprehensive Markdown report containing:
    1. Summary Table (Run / File, Category, Confidence, Mitigation)
    2. Detailed Failure Analysis
    3. Ready-to-Post GitHub Issue Draft
    """
    items = data_input if isinstance(data_input, list) else [data_input]

    report = []
    report.append("# 📊 CI/CD Flaky Test Analysis Report")
    report.append(f"*Generated automatically by [ci-flake-agent](https://github.com/RK0297/ci-flake-agent)*\n")

    # 1. Summary Table
    report.append("## 📈 Flake Summary Table\n")
    report.append("| Run / File | Failure Category | Confidence | Suggested Mitigation |")
    report.append("| :--- | :--- | :--- | :--- |")

    category_counts = {}

    for item in items:
        run_name = item.get("input_log", item.get("run_id", "Run Log"))
        category = item.get("category", "real_bug")
        confidence = float(item.get("confidence", 0.0)) * 100
        mitigation = item.get("suggested_mitigation", "N/A")
        
        category_counts[category] = category_counts.get(category, 0) + 1
        badge = format_category_badge(category)
        
        report.append(f"| `{run_name}` | {badge} | `{confidence:.1f}%` | {mitigation} |")

    report.append("\n---\n")

    # 2. Detailed Root Cause Breakdown
    report.append("## 🔍 Detailed Root Cause Breakdown\n")

    for i, item in enumerate(items, 1):
        run_name = item.get("input_log", item.get("run_id", f"Run #{i}"))
        category = item.get("category", "real_bug")
        confidence = float(item.get("confidence", 0.0)) * 100
        explanation = item.get("explanation", "N/A")
        mitigation = item.get("suggested_mitigation", "N/A")

        report.append(f"### {i}. `{run_name}`")
        report.append(f"- **Category:** {format_category_badge(category)}")
        report.append(f"- **Confidence:** `{confidence:.1f}%`")
        report.append(f"- **Explanation:** {explanation}")
        report.append(f"- **Recommended Fix:** {mitigation}\n")

    report.append("---\n")

    # 3. Ready-to-Post GitHub Issue Body
    primary_category = max(category_counts, key=category_counts.get) if category_counts else "Flaky Tests"
    
    report.append("## 📝 Ready-to-Post GitHub Issue Draft\n")
    report.append("Copy and paste the markdown block below directly into a GitHub Issue:\n")
    report.append("```markdown")
    report.append(f"### [CI Flake] Automated Analysis: {primary_category.replace('_', ' ').title()} Detected")
    report.append("")
    report.append("**Flaky Test Suite Summary:**")
    report.append(f"- **Total Evaluated Runs:** {len(items)}")
    report.append(f"- **Dominant Flake Category:** `{primary_category}`")
    report.append("")
    report.append("#### Top Findings & Mitigations:")
    for item in items[:3]:
        run_name = item.get("input_log", item.get("run_id", "Run Log"))
        cat = item.get("category", "real_bug")
        mit = item.get("suggested_mitigation", "N/A")
        report.append(f"- **`{run_name}`** (`{cat}`): {mit}")
    report.append("")
    report.append("*Report generated by [ci-flake-agent](https://github.com/RK0297/ci-flake-agent)*")
    report.append("```\n")

    return "\n".join(report)


def post_to_github_issue(repo: str, issue_number: int, content: str, token: str = "") -> bool:
    """Post generated report as a comment on a GitHub Issue/PR via REST API."""
    headers = {
        "Accept": "application/vnd.github.v3+json",
        "Authorization": f"Bearer {token}"
    }
    url = f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments"
    print(f"[POST] Commenting report on GitHub Issue #{issue_number} in '{repo}'...")

    response = requests.post(url, headers=headers, json={"body": content})
    if response.status_code == 201:
        comment_url = response.json().get("html_url")
        print(f"[SUCCESS] Successfully posted comment: {comment_url}")
        return True
    else:
        print(f"[ERROR] Failed to post comment: Status {response.status_code} - {response.text}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(description="Generate Markdown report & GitHub issue draft from analysis JSON.")
    parser.add_argument("--input", required=True, help="Path to analysis JSON file or batch_analysis.json")
    parser.add_argument("--output", default="reports/sample_report.md", help="Path to output markdown report")
    parser.add_argument("--post", action="store_true", help="Bonus: Auto-post report comment to GitHub issue/PR (default: off)")
    parser.add_argument("--repo", help="Repository in format 'owner/repo' (required if --post is set)")
    parser.add_argument("--issue-id", type=int, help="GitHub Issue or PR number to comment on (required if --post is set)")
    parser.add_argument("--token", help="GitHub Personal Access Token")

    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"[ERROR] Input file '{args.input}' does not exist.", file=sys.stderr)
        sys.exit(1)

    with open(args.input, "r", encoding="utf-8") as f:
        data = json.load(f)

    report_md = generate_markdown_report(data)

    os.makedirs(os.path.dirname(args.output) if os.path.dirname(args.output) else ".", exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(report_md)

    print(f"[SUCCESS] Markdown report & GitHub issue draft saved to {args.output}")

    if args.post:
        if not args.repo or not args.issue_id:
            print("[ERROR] --repo and --issue-id are required when --post flag is enabled.", file=sys.stderr)
            sys.exit(1)
            
        token = get_auth_token(args.token)
        if not token:
            print("[ERROR] GitHub token required for posting comments.", file=sys.stderr)
            sys.exit(1)
            
        post_to_github_issue(args.repo, args.issue_id, report_md, token)


if __name__ == "__main__":
    main()
